-- 인증 이전의 스텁 사용자 데이터를 제거한다.
--
-- getCurrentUserId() 가 고정값 "1" 을 돌려주던 동안 등록된 행들이다. 장소는
-- 등록한 사람에게만 보이도록 스코핑되었으므로("내 장소만"), user_id = '1' 인
-- 행은 그에 대응하는 auth.users 레코드가 없어 앞으로 누구에게도 보이지 않는다.
-- 조회되지 않는 데이터를 남겨 두면 나중에 "왜 places 에 행이 있는데 지도가
-- 비어 있나" 하는 혼란만 남으므로 지운다.
--
-- 이 행들이 참조하던 Storage 객체는 여기서 지우지 않는다. storage.objects 를
-- SQL 로 삭제하면 메타데이터 행만 사라지고 실제 파일은 백엔드에 남아 접근할
-- 수 없는 상태로 방치된다. 파일 삭제는 Storage API 로 해야 하며,
-- scripts/purge-stub-storage.mjs 가 그 작업을 한다(1회성).
delete from public.places where user_id = '1';
